### ISSUE TITLE
PC Number Scroll Issue

### ISSUE THREAD

**Issue by iuravic** [Morningstar-Engineering/Desktop-Midi-Editor#1]
Hi folks, 
I'm trying to send incremental and decremental Program Changes to scroll through my Axe Fx II XL+ presets.

I'd like to use two switches on my Morningstar MC8, one to continually increment PCs, and scroll through Axe's presets upwards, and the other to continually decrement PCs, and scroll through Axe's presets downwards.

I've set up these two switches and presets/messages:

![image](https://user-images.githubusercontent.com/29167323/109472703-c383fe80-7a72-11eb-92d8-b395ee682492.png)

![image](https://user-images.githubusercontent.com/29167323/109472722-c8e14900-7a72-11eb-92ad-1796c2ed5ec8.png)

but the MIDI Monitor shows that `127` data/value is being sent when pressing any of these two switches, and the value doesn't change. I can see that effect on my Axe -- preset `127` gets selected, and stays on that one:
![image](https://user-images.githubusercontent.com/29167323/109472849-ee6e5280-7a72-11eb-9a6f-2058be9e5ef3.png)

Am I doing something wrong?

Thanks!

I am using:
- MC8 with v3..8.3 latest firmware
- Morningstar MIDI Editor desktop, latest release v1.1.2
- Axe Fx II XL+ (with the latest firmware "Ares 2.00")

**Comment by tyzjames** [comment]
You'll need to set up the counter mix and max values in the Controller
settings, under the counters tab

**Comment by iuravic** [comment]
Yes, that did the trick! Thanks @tyzjames !

**Comment by iuravic** [comment]
Thanks so much James.
Keep on the great work, and have a nice day! :)
Ivan
